"""
Auther: Uri Sorek
Description: this module contains constant signs for the calculator.
"""
__all__ = ["PLUS_OPERATOR", "MINUS_OPERATOR", "MULTIPLY_OPERATOR", "DIVIDE_OPERATOR", "POWER_OPERATOR",
           "MODULO_OPERATOR", "MIN_OPERATOR", "MAX_OPERATOR", "AVG_OPERATOR", "FACTORIAL_OPERATOR", "TILDA_OPERATOR",
           "ADD_DIGIT_OPERATOR", "OPENER_BRACKET", "CLOSER_BRACKET", "SIGN_MINUS", "DECIMAL_POINT"]
PLUS_OPERATOR = '+'
MINUS_OPERATOR = '-'
MULTIPLY_OPERATOR = '*'
DIVIDE_OPERATOR = '/'
POWER_OPERATOR = '^'
MODULO_OPERATOR = '%'
MIN_OPERATOR = '&'
MAX_OPERATOR = '$'
AVG_OPERATOR = '@'
FACTORIAL_OPERATOR = '!'
TILDA_OPERATOR = '~'
ADD_DIGIT_OPERATOR = '#'
OPENER_BRACKET = '('
CLOSER_BRACKET = ')'
SIGN_MINUS = 'u'
DECIMAL_POINT = '.'
